default:
  'datasets':
    - 'datasets/worms_2017-04-25/'
    - 'datasets/worms_2018-10-24/'
    - 'datasets/worms_2019_08_15/'
  'experiment.days': 'user_defined_feature_labels_and_categories/experiment.days.perPlate'
  'morphological-features': 'user_defined_feature_labels_and_categories/morphological_features.csv'
  'stimuli-features': 'user_defined_feature_labels_and_categories/stimuli_features.csv'
  '2nd-alleles': "user_defined_feature_labels_and_categories/2nd_allele_OC_Strain_genotype_labels_0909_2019.txt"
  'data': 'processed_data/'
  'plots': 'plots/'
  'feature-subcategories': 'user_defined_feature_labels_and_categories/ASD_phenomics_feature_subcategories_0101_2019.tsv'
  'feature-subcategories-labels': 'user_defined_feature_labels_and_categories/ASD_phenomics_feature_labels_subcategories_0101_2019.tsv'
  'strain-genotype-labels': 'user_defined_feature_labels_and_categories/Strain_genotype_labels_withSource_0209_2019.tsv'
  'asd-confidence-categories': 'user_defined_feature_labels_and_categories/SFARI_Satterstrom_Strain_genotype_labels_0915_2019.tsv'
  'asd-categories-colors': 'user_defined_feature_labels_and_categories/ASD_categories_colors.csv'
  'asd-confidence-colors': 'user_defined_feature_labels_and_categories/ASD_confidence_colors_19092019.csv'
  'clustering':
    'ncpu': 30
    'nboot': 50000
    'alpha': 0.95
    'seed': 0
    'plots': 'pvclust_plots/'
  'tsne':
    'seed2D': 119
    'seed3D': 85
    'theta': 0
    'perplexity': 20
    'pca': T
    'output-directory': 'tsne_plots/'
  'colors':
      'baseline-locomotion': '#636363'
      'morphology': '#000000'
      'spontaneous-recovery_learning-retention': '#76b6f4'
      'initial-sensitivity': '#1c86ee'
      'habituation-learning': '#d1e6fb'
      'gwb-scheme': 
        - 'gray39'
        - 'white'
        - 'dodgerblue2'
      'heatmap-scheme':
        - 'dodgerblue2'
        - 'black'
        - 'yellow'
  'constants':
    'wildtypes': 
      - "N2"
      - "N2-10"
      - "N2-3"
      - "N2-4"
      - "N2-6"
      - "N2-7"
      - "N2-8"
      - "N2-9"
      - "N2-5"
      - "N2-2"
      - "N2-11"
      - "N2-12"
      - "N2-13"
      - "N2-14"
      - "N2-15"
      - "N2-16"
      - "N2-17"
      - "N2-20"
      - "N2-18"
      - "N2-24"
      - "N2-23"
      - "N2-21"
      - "N2-19"
      - "N2-22"
    'featureset':
      'computed':
        - "probNR"
        - "probSR"
      'discrete':
        - "plate"
        - "line"
        - "gene"
        - "rowStimuli"
        - "line.y"
        - "gene.y"
        - "number"
        - "goodnumber"
        - "time"
        - "nWormAR"
        - "nWormNR"
        - "nWormSR"
        - "probNR"
        - "probSR"
      'redundant':
        - "DistSE"
        - "Dist0Q"
        - "Dist1Q"
        - "Dist2Q"
        - "Dist3Q"
        - "DistTop1Pct"
        - "DurationSE"
        - "Duration0Q"
        - "Duration1Q"
        - "Duration2Q"
        - "Duration3Q"
        - "DurationTop1Pct"
        - "ratioAR"
        - "ratioNR"
      'learning':
        - "initRespPb"
        - "initRespDuration"
        - "initRespSpeed"
        - "initRespDistance"
        - "habituationPb"
        - "habituationDuration"
        - "habituationSpeed"
        - "habituationDistance"
        - "spontPb"
        - "spontDuration"
        - "spontSpeed"
        - "spontDistance"

