install.packages("config")
install.packages("here")
install.packages("reshape2")

install.packages("dplyr")
install.packages("xtable")
install.packages("ggplot2")
install.packages("pvclust")
install.packages("pdist")
install.packages("devtools")
install.packages("ggfortify") 
install.packages("RColorBrewer")
install.packages("cluster")
install.packages("PerformanceAnalytics")
install.packages("ggrepel")
install.packages("tidyr")