---
title: "Correlation matrices"
output:
  html_document: default
  pdf_document: default
subtitle: version 1.0
---
  
```{r setup, include=FALSE}
# Rmd-specific settings
library(here)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here() )

options(width = 1920)

```

```{r init, include=FALSE, echo=FALSE}
# Import and Load
source("preprocessing_scripts/utils.R")

t.stat <- readObjectAsMatrix("t.stat") 

```


```{r prepare-corrmatrices, echo=FALSE, fig.width=12, fig.height=9}

t.correlation.mutant = cor(t.stat[!grepl(x = rownames(t.stat), pattern = "^N2"), ])
diag(t.correlation.mutant) = NA

t.correlation.N2 = cor(t.stat[grepl(x = rownames(t.stat), pattern = "^N2"), ])
diag(t.correlation.N2) = NA

corr.matrix.feature.colors = as.vector(sapply(feature.class$Class, function(x) as.character(feature.class.colormap[x])))
feature.class.df = data.frame(Feature=  feature.class$Class)
rownames(feature.class.df) <- feature.class$Feature
```

## Correlation matrices {.tabset}

### N2 replicates only
```{r render-N2-corrmatrices, echo=FALSE, fig.width=12, fig.height=9}

correlationHeatmap(t.correlation.N2, title = "Feature correlation (N2 replicates)")
```

### Excluding N2 replicates
```{r render-mutant-corrmatrices, echo=FALSE, fig.width=12, fig.height=9}
correlationHeatmap(t.correlation.mutant,title = "Feature correlation (No N2 replicates)")
```
